run:
  timeout: 5m
  modules-download-mode: mod
  tests: true  
  skip-files:
    - config.go
  skip-dirs:
    - build
    - db
    - deploy
    - docker
    - helm
    - kind
    - test-int
output:
  format: colored-line-number

issues:
  exclude:
    - Using the variable on range scope .* in function literal

linters:
  disable-all: true
  enable:
    - bodyclose    
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gocritic
    - goimports
    - gosec
    - gosimple
    - goconst
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - varcheck 
    - unconvert
    - unparam
    - whitespace

  # don't enable:
    # - gofmt (goimports does the same)
    # - golint (stylecheck is a replacement for golint)
    # - prealloc (premature optimization)
    # - unused (causes unstable results of staticcheck)