apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart.fullname" . }}
      app.kubernetes.io/name: {{ include "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.internal.port | quote }}
        dapr.io/app-port: "{{ .Values.dapr.listenPort }}"
        dapr.io/app-id: {{ include "chart.fullname" . }}
        dapr.io/log-level: {{ .Values.dapr.logLevel }}
        dapr.io/metrics-port: {{ .Values.dapr.metricsPort | quote }}
        dapr.io/enabled: "{{ .Values.dapr.enabled }}"
        dapr.io/app-protocol: "grpc"
      labels:
        app: {{ include "chart.fullname" . }}
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.rbac.enable }}
      serviceAccountName: {{ include "chart.fullname" . }}-serviceaccount
      {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:

            - name: POSTGRES_USER
              value: {{ .Values.db.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-db-key
                  key: password
            - name: POSTGRES_SSLMODE
              value: {{ .Values.db.sslMode }}
            - name: POSTGRES_HOST
              value: "{{ tpl (.Values.db.server | required "must set db.server") . }}"
            - name: POSTGRES_PORT
              value: {{ .Values.db.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
            - name: dsn
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=$(POSTGRES_SSLMODE)

          ports:
            - name: grpc
              containerPort: {{ .Values.app.grpcPort }}
              protocol: {{ .Values.grpcProtocol }}
            - name: http
              containerPort: {{ .Values.app.httpPort }}
              protocol: {{ .Values.httpProtocol }}
            - name: internal
              containerPort: {{ .Values.internal.port }}
          args:
            - "--database.dsn=$(dsn)"
            - "--dapr.pubsub.name={{ .Values.dapr.pubsubName }}"
            - "--dapr.grpcPort={{ .Values.dapr.grpcPort }}"
            - "--dapr.publish.topic={{ .Values.dapr.topics.publish }}"
            - "--dapr.appPort={{ .Values.dapr.listenPort }}"
            - "--dapr.subscribe.topic={{ .Values.dapr.topics.subscribe }}"
{{- if .Values.internal.enable }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.internal.port }}
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.internal.port }}
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
