apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "storage"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "1250"
        dapr.io/log-level: "debug"
        dapr.io/metrics-port: "9091"	
    spec:
      containers:
      - name: storage
        image: 542011/storage
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  selector:
    app: storage
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30003
