apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
   matchLabels:
    app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:latest
          env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: password
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    app: db
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001