// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: infoblox-training-task-3/portal/pkg/pb/service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_UNKNOWN  Command = 0
	Command_INFO     Command = 1
	Command_UPTIME   Command = 2
	Command_REQUESTS Command = 3
	Command_MODE     Command = 4
	Command_TIME     Command = 5
	Command_RESET    Command = 6
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "UNKNOWN",
		1: "INFO",
		2: "UPTIME",
		3: "REQUESTS",
		4: "MODE",
		5: "TIME",
		6: "RESET",
	}
	Command_value = map[string]int32{
		"UNKNOWN":  0,
		"INFO":     1,
		"UPTIME":   2,
		"REQUESTS": 3,
		"MODE":     4,
		"TIME":     5,
		"RESET":    6,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_infoblox_training_task_3_portal_pkg_pb_service_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_infoblox_training_task_3_portal_pkg_pb_service_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescGZIP(), []int{0}
}

type Service int32

const (
	Service_UNKNOW    Service = 0
	Service_PORTAL    Service = 1
	Service_RESPONDER Service = 2
	Service_STORAGE   Service = 3
)

// Enum value maps for Service.
var (
	Service_name = map[int32]string{
		0: "UNKNOW",
		1: "PORTAL",
		2: "RESPONDER",
		3: "STORAGE",
	}
	Service_value = map[string]int32{
		"UNKNOW":    0,
		"PORTAL":    1,
		"RESPONDER": 2,
		"STORAGE":   3,
	}
)

func (x Service) Enum() *Service {
	p := new(Service)
	*p = x
	return p
}

func (x Service) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service) Descriptor() protoreflect.EnumDescriptor {
	return file_infoblox_training_task_3_portal_pkg_pb_service_proto_enumTypes[1].Descriptor()
}

func (Service) Type() protoreflect.EnumType {
	return &file_infoblox_training_task_3_portal_pkg_pb_service_proto_enumTypes[1]
}

func (x Service) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service.Descriptor instead.
func (Service) EnumDescriptor() ([]byte, []int) {
	return file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescGZIP(), []int{1}
}

type HandlerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command Command `protobuf:"varint,1,opt,name=command,proto3,enum=portal.Command" json:"command"`
	Value   string  `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	Service Service `protobuf:"varint,3,opt,name=service,proto3,enum=portal.Service" json:"service"`
}

func (x *HandlerRequest) Reset() {
	*x = HandlerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infoblox_training_task_3_portal_pkg_pb_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerRequest) ProtoMessage() {}

func (x *HandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infoblox_training_task_3_portal_pkg_pb_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerRequest.ProtoReflect.Descriptor instead.
func (*HandlerRequest) Descriptor() ([]byte, []int) {
	return file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescGZIP(), []int{0}
}

func (x *HandlerRequest) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_UNKNOWN
}

func (x *HandlerRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *HandlerRequest) GetService() Service {
	if x != nil {
		return x.Service
	}
	return Service_UNKNOW
}

type HandlerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Service  string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *HandlerResponse) Reset() {
	*x = HandlerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infoblox_training_task_3_portal_pkg_pb_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerResponse) ProtoMessage() {}

func (x *HandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infoblox_training_task_3_portal_pkg_pb_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerResponse.ProtoReflect.Descriptor instead.
func (*HandlerResponse) Descriptor() ([]byte, []int) {
	return file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescGZIP(), []int{1}
}

func (x *HandlerResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *HandlerResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_infoblox_training_task_3_portal_pkg_pb_service_proto protoreflect.FileDescriptor

var file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDesc = []byte{
	0x0a, 0x34, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x6c, 0x6f, 0x78, 0x2d, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x33, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x0e,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x29, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x47, 0x0a, 0x0f, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2a, 0x59, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49,
	0x4e, 0x46, 0x4f, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x54, 0x49, 0x4d, 0x45, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x53, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x4d, 0x4f, 0x44, 0x45, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x49, 0x4d,
	0x45, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x53, 0x45, 0x54, 0x10, 0x06, 0x2a, 0x3d,
	0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x4f, 0x52, 0x54, 0x41, 0x4c, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x10, 0x03, 0x32, 0x52, 0x0a,
	0x06, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x12, 0x48, 0x0a, 0x07, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x6f, 0x72,
	0x74, 0x61, 0x6c, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x0c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x06, 0x22, 0x01, 0x2f, 0x3a, 0x01,
	0x2a, 0x42, 0x2b, 0x5a, 0x29, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x6c, 0x6f, 0x78, 0x2d, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x33, 0x2f, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescOnce sync.Once
	file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescData = file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDesc
)

func file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescGZIP() []byte {
	file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescOnce.Do(func() {
		file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescData)
	})
	return file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDescData
}

var file_infoblox_training_task_3_portal_pkg_pb_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_infoblox_training_task_3_portal_pkg_pb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_infoblox_training_task_3_portal_pkg_pb_service_proto_goTypes = []interface{}{
	(Command)(0),            // 0: portal.Command
	(Service)(0),            // 1: portal.Service
	(*HandlerRequest)(nil),  // 2: portal.HandlerRequest
	(*HandlerResponse)(nil), // 3: portal.HandlerResponse
}
var file_infoblox_training_task_3_portal_pkg_pb_service_proto_depIdxs = []int32{
	0, // 0: portal.HandlerRequest.command:type_name -> portal.Command
	1, // 1: portal.HandlerRequest.service:type_name -> portal.Service
	2, // 2: portal.Portal.Handler:input_type -> portal.HandlerRequest
	3, // 3: portal.Portal.Handler:output_type -> portal.HandlerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_infoblox_training_task_3_portal_pkg_pb_service_proto_init() }
func file_infoblox_training_task_3_portal_pkg_pb_service_proto_init() {
	if File_infoblox_training_task_3_portal_pkg_pb_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infoblox_training_task_3_portal_pkg_pb_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infoblox_training_task_3_portal_pkg_pb_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infoblox_training_task_3_portal_pkg_pb_service_proto_goTypes,
		DependencyIndexes: file_infoblox_training_task_3_portal_pkg_pb_service_proto_depIdxs,
		EnumInfos:         file_infoblox_training_task_3_portal_pkg_pb_service_proto_enumTypes,
		MessageInfos:      file_infoblox_training_task_3_portal_pkg_pb_service_proto_msgTypes,
	}.Build()
	File_infoblox_training_task_3_portal_pkg_pb_service_proto = out.File
	file_infoblox_training_task_3_portal_pkg_pb_service_proto_rawDesc = nil
	file_infoblox_training_task_3_portal_pkg_pb_service_proto_goTypes = nil
	file_infoblox_training_task_3_portal_pkg_pb_service_proto_depIdxs = nil
}
