// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: infoblox-training-task-3/storage/pkg/pb/service.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on HandlerRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *HandlerRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Command

	// no validation rules for Value

	// no validation rules for Service

	return nil
}

// HandlerRequestValidationError is the validation error returned by
// HandlerRequest.Validate if the designated constraints aren't met.
type HandlerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HandlerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HandlerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HandlerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HandlerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HandlerRequestValidationError) ErrorName() string { return "HandlerRequestValidationError" }

// Error satisfies the builtin error interface
func (e HandlerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHandlerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HandlerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HandlerRequestValidationError{}

// Validate checks the field values on HandlerResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *HandlerResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Response

	// no validation rules for Service

	return nil
}

// HandlerResponseValidationError is the validation error returned by
// HandlerResponse.Validate if the designated constraints aren't met.
type HandlerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HandlerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HandlerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HandlerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HandlerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HandlerResponseValidationError) ErrorName() string { return "HandlerResponseValidationError" }

// Error satisfies the builtin error interface
func (e HandlerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHandlerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HandlerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HandlerResponseValidationError{}
