app:
  id: responder
server:
  address: 0.0.0.0
  port: 9090
gateway:
  enable: false
  address: 0.0.0.0
  port: 8080
  endpoint: /responder/v1/
  swaggerFile: ./www/service.swagger.json
database:
  enable: false
  dsn: 
  type: postgres
  address: 0.0.0.0
  port: 5432
  name: responder
  user: postgres
  password: postgres
  ssl: disable
  option:
atlas.pubsub:
  enable: false
  address: atlas.pubsub
  port: 5555 
  publish: topic
  subscribe: topic
atlas.authz:
  enable: false
  address: themis.authz
  port: 5555
atlas.audit:
  enable: false
  address: atlas.audit
  port: 5555
atlas.tagging:
  enable: false
  address: atlas.tagging
  port: 5555
internal:
  enable: true
  address: 0.0.0.0
  port: 8081
  health: /healthz
  readiness: /ready
config:
  source: deploy
  secret.file: 
logging:
  level: debug